import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/home.module.css";
import { Heading } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Heading>Home</Heading>
      </main>
    </>
  );
}
